#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=R2D2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --time=3:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# Activate your environment
source deactivate
source activate relfm-v1.0

# set default value of ckpt
# ckpt=trained_models/r2d2_WASF_N16.pt
# ckpt=trained_models/finalmodelC3_epoch_2_4x16_1x32_1x64_2x128.pt
# ckpt=trained_models/finalmodelC4_epoch_5_4x16_1x32_1x64_2x128.pt
# ckpt=trained_models/finalmodelC8_epoch_1_4x16_1x32_1x64_2x128.pt
ckpt=trained_models/finalmodelSO2_epoch_17_4x16_1x32_1x64_2x128.pt

# set default value of data_dir
data_dir=$PWD/data/hpatches-sequences-release/


echo "----------------------------------------"
echo "Running inference on hpatches dataset"
echo "Checkpoint: $ckpt"
echo "Data directory: $data_dir"
echo "----------------------------------------"

# Run your code
# WARNING: This needs to be run from the root of the repo

# set checkpoint path
model_ckpt_path=$PWD/$ckpt

# set output path
output_dir=$HOME/outputs/rotation-equivariant-lfm

python relfm/inference/r2d2_on_hpatches.py \
    --data_dir $data_dir \
    --model_ckpt_path $model_ckpt_path \
    --output_dir $output_dir \
    --downsize \
    --imsize 300 
